import type { ChunkUploadOptions, ChunkUploaderEventMap, ChunkUploaderState, Unsubscribe, UploadResult } from './types';
export declare class ChunkUploader {
    progress: number;
    isUploading: boolean;
    isPaused: boolean;
    isComplete: boolean;
    error: string | null;
    uploadId: string | null;
    uploadedChunks: number;
    totalChunks: number;
    currentFile: File | null;
    private readonly maxConcurrent;
    private readonly autoRetry;
    private readonly maxRetries;
    private readonly headers;
    private readonly withCredentials;
    private readonly context?;
    private readonly chunkSizeOverride?;
    private readonly endpoints;
    private abortController;
    private pendingChunks;
    private serverChunkSize;
    private lastFile;
    private lastMetadata?;
    private listeners;
    constructor(options?: ChunkUploadOptions);
    on<K extends keyof ChunkUploaderEventMap>(event: K, callback: (data: ChunkUploaderEventMap[K]) => void): Unsubscribe;
    private emit;
    private emitStateChange;
    getState(): ChunkUploaderState;
    private getHeaders;
    private fetchJson;
    private initiateUpload;
    private uploadSingleChunk;
    private uploadChunks;
    private fetchStatus;
    upload(file: File, metadata?: Record<string, unknown>): Promise<UploadResult>;
    pause(): void;
    resume(): void;
    cancel(): void;
    retry(): void;
    destroy(): void;
}
